// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  // import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCCFcwQ0r2_cJn1_BgIN89UvnOjaIarks',
    appId: '1:875145942508:android:93f19b33456d8a5b9a5cc9',
    messagingSenderId: '875145942508',
    projectId: 'talabaty-d339f',
    databaseURL: 'https://talabaty-d339f-default-rtdb.firebaseio.com',
    storageBucket: 'talabaty-d339f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDad23k6CxOyEKP0KnJzkZ4IKaW5fPlTdk',
    appId: '1:875145942508:ios:fa70c224697573be9a5cc9',
    messagingSenderId: '875145942508',
    projectId: 'talabaty-d339f',
    databaseURL: 'https://talabaty-d339f-default-rtdb.firebaseio.com',
    storageBucket: 'talabaty-d339f.appspot.com',
    iosClientId: '875145942508-6koiehecslv043iotsl0hasittuch3jj.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationOfSupport',
  );
}
